[build]
base = ""             # <--- This should be empty or removed
command = "cd client && npm install && npm run build"
publish = "client/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200